Include document with thumb in InputMessage
Lonami/grammers pull request #169
Opened 2023-02-22 07:13 UTC by sekzerd

When I upload a video, the thumb is missing. please add the method so that we can upload video with thumb.

2023-02-22 16:43 UTC, Lonami requested changes

2023-02-23 08:05 UTC, sekzerd commented on lib/grammers-client/src/types/input_message.rs
> +    pub fn document_thumb(mut self, file: Uploaded, thumb: Option<Uploaded>) -> Self {
That's right. I adjust that function, the same as  ```.attribute()```

2023-02-23 13:45 UTC, Lonami approved these changes

2023-02-23 13:46 UTC, merged

2023-02-23 13:46 UTC, Lonami commented
Thanks!