RPC 500 error handling
Lonami/grammers pull request #190
Opened 2023-07-08 04:49 UTC by tingfeng-key

RPC 500 error handling

2023-07-08 08:34 UTC, Lonami requested changes

2023-07-08 08:34 UTC, Lonami commented on lib/grammers-client/src/client/updates.rs
> +                    Err(InvocationError::Rpc(rpc_error)) if rpc_error.code.eq(&500) => {
Could be just `== 500`.

2023-07-09 06:12 UTC, tingfeng-key commented
I want to add a log to him, but I don't know what is more appropriate to output

2023-07-09 09:09 UTC, Lonami commented
You can probably log a warning, since this error should hopefully be rare enough.

2023-07-09 09:53 UTC, tingfeng-key commented
I have added it, you can see if you need to modify it

2023-07-09 18:09 UTC, Lonami commented on lib/grammers-client/src/client/updates.rs
> +                        log::warn!("rpc 500 err: {:#?}", rpc_error);
```suggestion
                        log::warn!("Telegram is having internal issues: {:#?}", rpc_error);
```

2023-07-09 19:00 UTC, merged