Upload speed optimalizations
Lonami/grammers pull request #86
Opened 2021-08-25 19:28 UTC by Marekkon5

- SIMD in encryption (still not 100% like decryption, but faster than before)
- Directly generate uncompressed GZip for larger chunks
- Add connections parameter to upload_stream, instead of using global static

2021-08-30 08:40 UTC, Marekkon5 commented
Sorry for delays, did it the "proper way", set the default to None = always compress.

2021-08-30 15:15 UTC, Lonami commented on lib/grammers-client/src/client/files.rs
> +    /// let uploaded_file = client.upload_stream(&mut stream, size, "sleep.jpg".to_string(), 4).await?;
Eh we should figure out something nicer than this later on.

2021-08-30 15:16 UTC, Lonami commented on lib/grammers-crypto/src/lib.rs
> +        vec![plaintext, &random_padding[..padding_len]].concat()
This might be worth a comment, as I wouldn't expect this to have a large performance impact.

2021-08-30 15:19 UTC, Lonami commented on lib/grammers-mtproto/src/mtp/encrypted.rs
> +    /// Configures the min compression threshold for outgoing messages.
```suggestion
    /// Configures the lower bound of the compression threshold for outgoing messages.
```

Perhaps we should remove the `Option`? A value of `0` should do the same.

2021-08-30 15:21 UTC, Lonami commented on lib/grammers-mtproto/src/mtp/encrypted.rs
> +    /// Configures the max compression threshold for outgoing messages.
```suggestion
    /// Configures the upper bound of the compression threshold for outgoing messages.
    ///
    /// The message can be at most `threshold` bytes long for it to be compressed.
```

2021-08-30 15:22 UTC, Lonami commented on lib/grammers-mtproto/src/lib.rs
> +pub const DEFAULT_MAX_COMPRESSION_THRESHOLD: Option<usize> = None;
Rename as `MIN` / `MAX`?

2021-08-30 15:23 UTC, Lonami requested changes
> Sorry for delays, did it the "proper way", set the default to None = always compress.

I wanted to do it as well, but it looks like I've delayed even more.

Could you split the changes of compression and and encryption optimization into two though? Or rebase to have two proper commits so that I can merge the changes separatedly.

2023-09-27 17:21 UTC, Lonami commented
Gonna close this one since it's ancient. Can revisit in the future if there's interest.

2023-09-27 17:21 UTC, closed without merging